# Generated by Django 4.1.5 on 2023-02-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spam_Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
        ),
    ]
